### PR TITLE
feat(website): fix

### PR DESCRIPTION
**Pull request by daimond113**
i fixed ur website

### CODE REVIEW

**Comment by daimond113** [comment]
plz merge asap

**Comment by MuckyDriver** [comment]
F off NO REACT OK

**Comment by daimond113** [comment]
IT DIDNT ADD REACT

**Comment by daimond113** [comment]
I JUST FIXED UR WEBSITE

**Comment by lukadev-0** [comment]
you should merge this pr. it has some really good fixes that i can see.

**Pull request closed without merging**
